### ISSUE TITLE
BUG: Currently init process is broken

### ISSUE THREAD

**Issue by LowellMontgomery** [mcrosson/lr_plugin_computer_vision_tagging#2]
@mcrosson This would not be apparent for you, unless you were to delete the preferences for your plugin (not even sure where they are stored, but I've uninstalled the other one, thinking I would get to see the "initial install" state and found that my stored ClientID, etc, showed back up on re-installation. So removing a plugin and re-adding it is not enough (for you to be able to replicate this issue), but what happens is that, if you attempt to add and enable this plugin, it fails where it tries to concatenate the Client ID as a string.

![init-failure](https://cloud.githubusercontent.com/assets/9017652/19390088/e1770218-9226-11e6-8292-e65bcc7f4331.png)

Best practice, I think, is to set the defaults for all prefs in the InitPlugin script, not the PluginInfoProvider, but having tried that, I'm still not getting it working. The settings are not showing up now at all. So I've reverted my changes and only added a prefs setting that initializes the client ID and secret both to empty string; and now it fails even more oddly:
![arithmetic_error](https://cloud.githubusercontent.com/assets/9017652/19390197/5111d062-9227-11e6-8ddd-7e427756057b.png)
 
No file or line number... and that failure is happening if I just try to open the plugin manager. So I've removed the plugin, for now. @mcrosson Maybe you can determine if this is just a bug introduced in a recent commit to master... otherwise there may be something here that just doesn't play nice with Mac. I don't have time to debug this now, after all. I thought it would be a simple fix. But the closest I got to having it working, after refactoring the InfoProvider and PluginInit (work I reverted to check I hadn't broken it worse) was to have the settings panel show up and indicate this plugin was enabled, but it didn't display any of the settings fields.

**Comment by LowellMontgomery** [comment]
If you can identify what's needed to get the plugin working for me, I'll see if I can add on the functionality we discussed. I'll commit my current (very minor) changes which only provide an empty value for both client ID and client secret, so that we are not attempting to perform an operation on a nil value (the initial error seen), but currently that seems to expose a the further error.

**Comment by mcrosson** [comment]
Can you pull up the plugin preferences at all? There is usually a log in there that shows what might be the underlying cause of the error.

Also, I'll try to figure out how to delete the plugin preferences to try to re-create the error. Do you know by chance how to do that offhand?

**Comment by LowellMontgomery** [comment]
When I did have the prefs pane showing, it had no error messages at all. I know where you are talking about. But I also had no fields. That was after some refactoring, as I'd said, so I reverted and only provided a default value for the two Clarifai variables (ID/secret) and then the plugin manager wouldn't open, so clearly we were getting further, but failing somewhere unspecified for the "arithmetic on a boolean".

I'm not sure Adobe provides a way to remove prefs for just one plugin, though you might be able to empty them, programmatically to simulate a fresh start. I think they provide a simple way to clear preferences for Lightroom, which would include all plugins, I think.

**Comment by mcrosson** [comment]
Thanks for the feedback. I'll see if I can re-create the issues in a new catalog. Hopefully a new catalog that hasn't been abused a bit will provide some insights on the crashes.

**Comment by mcrosson** [comment]
@LowellMontgomery would you be willing/able to do the quick refactor of PluginInfoProvider and InitPlugin? I'd like to dig into this after I get off work today and I think having your refactored code will be a gain.

**Comment by LowellMontgomery** [comment]
@mcrosson I've made a pull request in the bugfix branch I created in my fork that will give you that much, then. 👍 

But I'm not sure that that will help much with the broken behavior I was seeing when I tried to install the plugin. Please let me know if/when you get to the bottom of this, since then I might be able to experiment with adding the new setting fields and associated functionality (actually I've added variables for the new fields, but left their initialization commented out in the default prefs table).

**Comment by mcrosson** [comment]
I'll be looking at this closer very soon. Thank you for the patch. I'll be looking at this over the weekend hopefully. I really want to get to the bottom of it an ensure you can use the plugin.

I did spend a little time on this during my lunch break today and I saw that a "fresh" copy of the plugin/catalog/prefs seems to cause failures in Windows but they aren't pop-up failures like you were seeing.

**Comment by mcrosson** [comment]
@LowellMontgomery I just pushed an update that addresses a ton of the errors that surfaced when first installing the plugin or running without proper API setup.

Can you download the latest sources/release and let me know if you get any further running the plugin?

**Comment by LowellMontgomery** [comment]
Still not appreciably further, really. 

![init-failure-update](https://cloud.githubusercontent.com/assets/9017652/19408904/4fe0481c-92c8-11e6-8b98-7dc1f4b882ed.png)

IMHO, the validation of the client secret and client ID (and token, etc) should only happen when we are ready to make a request... then it should give us sensible information about any bad configuration or other cause of failure. But validation happening on the setup screen is not necessary and means the plugin is trying to pull logic cycles before anyone is even using it… not at all ideal, right?

I'd suggest getting all that logic out of the settings panel. The setup page could flag a field that has been deemed responsible for a recent failure (e.g. try to run the export, but you have no client secret entered, then you set the an error flag in the prefs table; one which includes the Client-Secret field name and that could be used to highlight the field when the user returns to the setup panel (it could also possibly display a message).

**Comment by LowellMontgomery** [comment]
I've experimented some more, but haven't yet seen the preferences fields get rendered. I could commit my current state, which doesn't stop the plugin getting installed, but it indicates an error when attempting to enable. That error is "An error occurred while attempting to run one of the plug-in‚Äôs scripts.
PluginInfoProvider.lua:1: unexpected symbol near 'Ô'

Not sure where the garbage characters are coming from... maybe character encoding?

**Comment by mcrosson** [comment]
@LowellMontgomery The logic to verify the Clarifai API settings should only run when you click "Done" in the preferences dialog. However, the more I thought about it, the more I can see why you wouldn't want to run the validation at that point. I'll make an update to remove the logic from that section of the application. The good news is I already built some code to show an error and handle a bad API key while testing/fixing yesterday so we should have no problems on that front.

I agree on the encoding / line ending suggestion. I'll be updating the project to use UTF-8 as well as Unix line endings shortly.

**Comment by mcrosson** [comment]
@LowellMontgomery commit 05cfdffa207a973bca69cd4ced2d58f885499a3a just went in with each file's encoding set to UTF-8 and line endings set to Unix. Can you retry running the plugin?

Also, can you tweak InitPlugin to set the log_level to KmnUtils.LogTrace? I added a ton of log statements that show what methods/code is being run and I'm curious if it's dying in a specific spot. The log file should be in your home dir (root of it or Documents folder) and named info.kemonine.lrcvt.log . Hopefully the plugin will pickup on the init change and start logging useful information about what is or isn't running.

**Comment by LowellMontgomery** [comment]
@mcrosson I think the plugin had probably already managed to set preferences and failed after that. Anyway, nothing new was written to the log when I tried to enable the plugin, but the form fields also did not appear (totally empty pane in plugin manager, as we'd seen before). I restarted LR and attempted to open the Plugin Manager again and got the familiar same error about performing arithmetic on a boolean that I'd seen before, i.e. it's back to blocking the Plugin Manager. I had to delete the plugin to get the Plugin Manager to come back. I think that error may happen if there is some certain kind of syntax error, actually. Anyway, after removing it, I've got my copy of your repository back, but still getting no further with it loading up than I did before.

**Comment by mcrosson** [comment]
@LowellMontgomery can you try resetting your lightroom preferences and trying with a fresh catalog/prefs? I think starting 100% fresh with the preferences/catalog might help us narrow this down a bit further.

There is a standard location for the preferences file (I don't know where on mac though) which you can backup first before clearing prefs. I did this while doing my updates for first install.

**Comment by LowellMontgomery** [comment]
Right. Deleted prefs file and restarted it. Added the plugin and saw the blank pane (as before), but since it was reading the new prefs, I got some log output:

```
2016-10-15 19:39:14 +0000, INFO	Debug log enabled
2016-10-15 19:39:14 +0000, TRACE	InfoProvider.sectionsForTopOfDialog(viewFactory, properties)
2016-10-15 19:39:14 +0000, TRACE	InfoProvider.sectionsForBottomOfDialog(viewFactory, properties)
2016-10-15 19:39:14 +0000, TRACE	InfoProvider.endDialog(properties)
2016-10-15 19:39:14 +0000, INFO	Debug log enabled
2016-10-15 19:39:14 +0000, TRACE	InfoProvider.sectionsForTopOfDialog(viewFactory, properties)
2016-10-15 19:39:14 +0000, TRACE	InfoProvider.sectionsForBottomOfDialog(viewFactory, properties)
2016-10-15 19:39:25 +0000, TRACE	InfoProvider.endDialog(properties)
2016-10-15 19:39:25 +0000, INFO	Debug log enabled
2016-10-15 19:39:26 +0000, TRACE	InfoProvider.sectionsForTopOfDialog(viewFactory, properties)
2016-10-15 19:39:26 +0000, TRACE	InfoProvider.sectionsForBottomOfDialog(viewFactory, properties)
2016-10-15 19:39:30 +0000, TRACE	InfoProvider.endDialog(properties)
2016-10-15 19:39:30 +0000, INFO	Debug log enabled
2016-10-15 19:39:55 +0000, INFO	Debug log enabled
```

Now, I think it might be possible to have just gone into the preferences file and changed the log level from 2 to 4 or whatever, after finding the section for this plugin. (I'd need to look at the code, but that might make more sense than backing-up and deleting (next time).

**Comment by mcrosson** [comment]
What you're seeing is very strange, from that output everything is working correctly. Are you still receiving the attempt to perform arithmetic on boolean error?

Any chance you'd be willing to add a few more log lines in the PluginInfoProvider to see if you can narrow down the block of code causing the error?

**Comment by LowellMontgomery** [comment]
Yeah... I still get arithmetic on boolean error if I quit the Plugin Manager and re-open it; then I need to remove the plugin (from the directory that Lightroom had it installed from, not the default Modules directory) in order to deactivate and uninstall it. 

Anyway... if you push some changes that include log file edits, I could pull that in and try again. I used XCode's plist editor to modify the .plist file for Lightroom, digging inside to change the log_level for this plugin from 2 to 6. I still haven't seen any fields rendered (e.g. client ID and secret, etc) on the plugin manager / settings panel.

**Comment by mcrosson** [comment]
@LowellMontgomery I'll be putting together a separate branch for OSX compatibility in the next day or two for testing / fine tuning. I'm now on a mission to get this working on OSX and will make sure the next update has a ton of extra debugging so we can hopefully get to the bottom of this quickly. I'll keep you posted as I make progress and will work with you on the testing.

Also, to help with testing could you get me the Lightroom version you're using as well as the plugin preferences that are in your plist file? I only need the block of preferences specific to the plugin and I think between the Lightroom version, extra logging and preference values I should be able to sort out the exact crash.

**Comment by LowellMontgomery** [comment]
@mcrosson I'm using OS X 10.11, aka El Capitan with Lightroom CC 6.7 (Adobe Subscription). I've never seen anything like this, so have no idea why it is happening. Maybe we can some others to take a look at the code and issue and see if it can be replicated on other Mac OS systems before jumping to too many conclusions. They may be other explanations we haven't considered. But it sure would be nice to get at least one of these Clarifai-related plugins to work on both platforms ;-}

Preferences for Lightroom 6 on OS X are written to a file called `com.adobe.Lightroom6.plist`, which is stored in `~/Library/Preferences`, (where the `~` is short for `/Users/username`. The location and form is a bit different on Windows, so I'm not sure if you can open an editor to change them there.

This plugin writes gets preferences added to the Lightroom 6 .plist file under a key-name of `sdk_info.kemonine.lrcvt`. The following is the value stored under that key:

```
prefs = {
	auto_select_existing_tags = true,
	bold_existing_tags = true,
	clarifai_accesstoken = "",
	clarifai_clientid = "",
	clarifai_clientsecret = "",
	log_level = 6,
	sort = "prob",
	tag_window_height = 768,
	tag_window_show_probabilities = true,
	tag_window_width = 1024,
	thumbnail_size = 256,
}
```

I'm providing all of the above information so that any others helping get this stable on Mac / OS X are able to find the Lightroom preferences and details within it that relate to this plugin.

**Comment by LowellMontgomery** [comment]
@mcrosson Just verified that I'd had a couple extra pref items in my the list, but removing them does not affect the outcome. Loading the plugin results in same, regardless of what I try. I've also used Xcode to delete the whole element for this plugin and have verified that when I add the plugin again, that the preferences are correctly written. So it seems to be fine in that respect.
But still, if I add the plugin, it looks like this in the Plugin Manager:

![image](https://cloud.githubusercontent.com/assets/9017652/19417417/bd10d034-93ac-11e6-9af3-e9e6132b7892.png)

If I close the Plugin Manager and attempt to re-open it, I get that boolean arithmetic error message and the whole panel doesn't show up. (At which point the only workaround is to delete the plugin from its installed location—not the usual plugins location, since I'm running it from where my Git checkouts are stored, but I'm running other plugins this way without any issues like this—AND then re-open the Plugin Manager to remove it, at which point it shows there is a problem, but that's because the plugin files are gone).

**Comment by mcrosson** [comment]
@LowellMontgomery  thank you for all the extra info 👍 I really appreciate it. I don't have any assumptions about what's wrong but having the full detail on your setup is hugely helpful. I am on a mission to get this working under OSX at this point.

The good new is I got this when I opened the PluginInfoProvider.lua file this monrning
![codeerror](https://cloud.githubusercontent.com/assets/2058383/19418407/3982c396-9391-11e6-92d0-fd08c95d2aaa.png)

After a little digging I got the error to go away and I made a few other tweaks. Can you checkout the "phase_osx" branch and give the plugin a try?

**Comment by LowellMontgomery** [comment]
@mcrosson I'm a bit under the weather, so apologies (excuses) for the delayed response. I'm going to lie back down for a while, but (probably before you are up in the US), I'll give that a go. We should try to find some other Mac users with fewer experimental stuff on their systems to give this a go. It could also be a conflict of some kind (within my system)... at least some of the symptoms might be. I wrote another simple plugin yesterday which had a couple config fields, which also weren't displaying in the PM panel. 😕

**Comment by mcrosson** [comment]
@LowellMontgomery no rush on getting this working or doing the testing. I'd rather you feel well than under the weather. Hopefully it passes quickly.

That is odd another, simple plugin would not be showing the preferences UI. I wonder if creating a new user account and trying Lightroom + your new simple plugin + this one would be a good test case. It'll certainly tell you if something odd is happening with one of the others or your current account setup.

**Comment by LowellMontgomery** [comment]
@mcrosson Okay. I've had time to test that branch and unfortunately, it doesn't improve anything for me. Output is still the same (nothing new added to to debug the issue). Not sure what is going on, but it's definitely the only plugin I've seen that caused this kind of issue (where I would have to delete it to be able to go back to the Plugin Manager--that is a severe issue). I'd love to see if we can find others to replicate it.

**Comment by mcrosson** [comment]
@LowellMontgomery I found 2 small bugs that I sorted out first. I wanted to be sure they weren't the source before I started making bigger changes. Unfortunately the large majority of the code is just returning a table so additional debugging output isn't going to do much to help. The only way to figure out the cause is to start removing large chunks of the preferences and putting them back one at a time.

Alternatively, would you be willing to create another user account on your system and try light room + the plugin with a new account? That should tell us if it's Lightroom proper or your current account settings/preferences.

**Comment by LowellMontgomery** [comment]
@mcrosson 👍  I probably won't have time in the coming days to do much with this as I've got a lot of looming deadlines that need to take my priority (especially after being ill the past days), but I do like your roadmap and do hope that we can enlist some others to help us track down the nature of failures I've seen (and if they affect other Mac users, etc) as well as maybe figure out the Windows issues on the safx/Clarifai plugin. I definitely won't have time to mess around in a second user account anytime too soon. When I do have some time, I'll try the "divide and conquer" approach you suggested and remove (comment out) blocks of the pref table (in the other plugin where the Plugin Manager panel is not fully rendering--I can see more than a blank pane, but not the fields I expected to be added by the InfoProvider). If I can manage to get that working right, then it may also help identify a problem in this plugin (at least for Mac users?) Anyway, you may not see me for a few days, but I'll be back.

**Comment by mcrosson** [comment]
@LowellMontgomery Thank you for the heads up and best of luck with the deadlines.

If you can get the other plugin that you mention working as well as the before/after of what changes were ultimately necessary to make it work that should help me out in a big way. I am working on my end to get access to a Mac so I can hopefully do local testing myself.

As for the issue with safx, I tracked it down to the way it was using the image thumbnails from Lightroom instead of rending the actual photos. I probably could have patched it up but the menu driven approach I'm not as fond of. I think the export approach is a lot easier to work with day to day.

**Comment by LowellMontgomery** [comment]
@mcrosson Hi Mike,

Thanks for your understanding. I'll track what changes help resolve the odd issues with the other plugin, but I'm not sure how helpful the resolution will be for this issue, since:

1. The appearance of the plugin in the Plugin Manager is actually different (I was getting a totally blank pane in the PM with this plugin, whereas with the other, I had the standard fields to allow enabling/disabling, the info link, etc, just not the custom preset fields, and…
2. The plugin works, more-or-less as expected, with the default values set by my Init script.
3. I've never seen the "Boolean arithmetic" error before, nor had to move/delete a plugin from its install directory in order to access the Plugin Manager. This plugin is failing very hard (at least for me... possibly for other Mac users).

When I have time, the next thing I'll do for this issue is create some noise in Lightroom forums and direct them to this repository. Hopefully we can find an experienced Lightroom plugin developer who knows how to fix this issue.

You are right that the "export approach" is probably better, but it would be nice to offer a small patch to make the safx plugin Windows-friendly, especially if we are having trouble getting this one to be Mac-friendly, so if you have a tip for an approach to fix that and could verify that the changes produce a plugin that works, that would be great.

A bit off-topic: When we DO get the plugin working for me, do you think I need to generate a new "application" (separate Client ID and Secret) for this plugin, or do you think I could have both versions installed and allow them to use the same credentials?

Even more off-topic: Do you know if including some more metadata than copyright in the exported "thumbnail" might produce better tagging results? e.g., if they support it, Clarifai might be able to read (any included) GPS data and better decide if a location is the ruins of an old cathedral or of an old castle. It might also access a database that could say whether "old" or "ancient" are likely keywords for what's there (for example)... and if it could see accurate EXIF data, it might add "wide-angle view" or correctly identify the season and time of day, instead of indicating "dawn" and "winter", when a scene was actually shot on a mid-spring evening. I had photos taken the same day that were variously tagged "summer", "fall", "winter", depending on the lighting and amount of greenery that was visible (even though it was actually mid-spring). Or the Clarifai system might be able to better add keyword suggestions if there were already some appropriate keywords included with an image thumbnail, which could the Clarifai engine to be better "train" its recognition engine, e.g. goats were identified as cows in some of my landscape photos, despite being very obviously goats to a human observer (even in a small thumbnail), so its species identification is still pretty rudimentary, but with the right "seeds" it could provide other relevant terms.

Speaking of "feedback", I'm not sure if you have any plans to implement the Clarifai API "feedback" system, but that could be very useful, especially if someone were trying to "train" the recognition for a new "model". It would be awesome if we could click a button to "provide feedback" and select inaccurate terms and send them in a message along with the terms we were replacing them with (not "summer", but "spring" -- not "cows", but "goats"). Since this implies we have added other terms, we would need to "remember" the previous auto-tagging session(s) and reference the photo IDs for the feedback process.

Okay... I need to get back to the pile of tax papers on my desk... ;-)

**Comment by LowellMontgomery** [comment]
(When I read over the Clarifai API, I didn't notice anything that dealt with "more intelligent" recognition based on existing metadata, but it _does_ make sense, doesn't It?) Even adding keywords that correspond to the "model" we'd like to use (e.g. "food", "wedding", or "color"), might be useful and could allow a batch of photos sent to use a mix of models for the identification process, even "food"+"wedding"+"color" all at once. Anyway, I'll re-read the API and (probably) give them some suggested "improvement tickets" for v2. (Did you notice, btw, that there is are beta endpoints that support some new features? If the Beta API is stable enough, it may be an improvement over the current engine.)  BTW, once we get this stable and full-featured, it might also be good to get Clarifai's website to help promote this plugin (on their page of links to Git projects that implement the Clarifai API).

**Comment by mcrosson** [comment]
@LowellMontgomery 

I appreciate the offer to make some noise over in the Lightroom forums. Hopefully someone can pick out what is going on. The other option would be to comment/remove code in large chunks to try to narrow down what might be causing the problem. I've created an phase_osx_lowell branch that has most/all of the code commented or removed. Would you be willing to try that to see if the version number and/or activation blocks show? It's the start of what I'd do if I had a Mac on-hand to narrow down the underlying cause.

As for safx, I don't think it's a small patch to get Windows compatibility. The code would need to be updated to resize each image (similar to export) and then send the resized image upstream. The nature of the patch is part of the reason I went ahead and created a new plugin that leverages the export hooks. Export builds the resizing operations into the process and takes care of the heavy lifting for you as a developer. On top of that the thumbnails Lightroom generates on Windows are rejected by the Clarifai API. I was able to save the thumbnails to a non-temp directory by monkey patching the safx code and when I took the saved thumbnails and tried to open them in Photoshop or submit to Clarifiai I received nothing but errors.

As for offtopic, can we cull to separate issues in the future? I'd like to keep each issue narrow in focus going forward. 

Having said that:
- You shouldn't need to create a new application for both plugins. However having 2 apps created in Clarifai will let you see relative usage of each plugin. If you'd like to see a note added to the pro-tips section please let me know via a new ticket.
- I've not seen anything in the docs for the Clarifai API v1 or v2 that would suggest they are using the metadata from an image in any way. There is an option in my export dialog that lets you tune how much metadata goes out. You can always adjust that value to see how it affects tagging. I don't think it should have an effect though.
- I do have a note in the project plan to implement sending tags back to the upstream APIs for "feedback". However, I did look at the Clarifai/Microsoft Computer Vision/Google Vision APIs and their training/feedback mechanisms. I've thought about it a bit and I'm not sure if I want to incorporate those elements yet. I've created a new ticket for Clarifai's feedback mechanisms and training's for tracking going forward (#5). One of the tricks is how much do I expose via the export dialog, menus and/or extra dialogs in the workflow for submissions back to the upstream API. There are also quite a few feedback mechanisms that each have their own workflows. It gets especially crazy if I layer in the Microsoft or Google vision APIs. I'm tempted to say I'd rather be pulling only the tags from at least Clarifai/Microsoft prior to getting the feedback mechanisms up and running. I would take a patch if it's something you'd be willing to tackle ;) Especially now that the v2 API from Clarifai is in beta and includes custom models.
- I have tagged Clarifai on Twitter and one of their dev's starred the repo. I'll be pushing more with them once I have something confirmed working on Mac OS. Prior to that I'm content to stay under the radar a bit. I really don't want a flood of Mac users accusing me of breaking their Lightroom install just yet.

**Comment by LowellMontgomery** [comment]
I agree that the OT stuff *might* deserve new issues and definitely is not something to exhaustively discuss in *this* one, but I didn't want to clutter your project with "issues" (that may be non-issues). I have not taken a very deep look at the Clarifai API at this point, but I did browse more (last week or so) than I had before, after you talked up some of the features of the API that you were supporting with this plugin (e.g. support for different "models") which were not supported by the safx version.

Anyway...

![lrcvt-sort_of_working](https://cloud.githubusercontent.com/assets/9017652/19581027/8feeddea-972a-11e6-9a5b-abd3b0abb1f8.png)

So that ☝️  is some kind of improved situation, at least. 😀  The form renders now, but of course it needs the critical client ID/secret fields in order to be very usable. ;-)

When I actually have time to do so, I'll try uncommenting a chunk at a time till it breaks and try to see what's going on.

**Comment by mcrosson** [comment]
@LowellMontgomery I'm glad to see the progress. I think the biggest chunk to focus on is the missing code in PluginProviderInfo.lua. I stripped out damn near the whole preferences UI for the initial test.

**Comment by mcrosson** [comment]
@LowellMontgomery I managed to be granted access to an OSX El Capitan environment today. I was also able to re-create the issue you were seeing and get it FIXED! 👍 

I just pushed d901889bc305765db21c4d3dd014148c3bdca0e6 on the phase_osx branch. Can you checkout this branch and see if the plugin is working for you? I think I finally nailed it down. Once you confirm, I'll get the changes merged and push a new release.

I also deleted the phase_osx_lowell branch as it was no longer necessary.


![working el capitan](https://cloud.githubusercontent.com/assets/2058383/19621168/e97312b6-9859-11e6-9f9e-8c78c3523759.png)

**Comment by LowellMontgomery** [comment]
Awesome news! ... I'll pull and try re-installing the plugin. 👍

**Comment by LowellMontgomery** [comment]
Seems to be pretty much fixed, but there is an issue that prevents me using the plugin still. Perhaps you are already aware of this?
![skitched-20161022-230742](https://cloud.githubusercontent.com/assets/9017652/19622526/59517db4-98ac-11e6-83ba-449e510ab521.png)

I entered my Client ID and "Secret" and when I click on the "Verify Settings" button or "Generate New Access Token", I get this error, although you can also see the "Success" message that my ID and "Secret" were verified, so not sure what the problem is. But no access token seems to be generated and if I try to open other menu items provided by the plugin, I get the same error.

Other than that, this is great progress. That ☝️ ☝️  is still enough of a "blocker" to prevent me being able to add the features we'd discussed, but otherwise, it makes me feel like we are very close to that point. Maybe you already know what the problem is?

**Comment by mcrosson** [comment]
@LowellMontgomery that's an error message thrown by the plugin when it receives an invalid response back when generating a token. Can you set your log level to "Trace" and re-try? If it pops up again, take a look at the log file, there should be a json response in the log that will tell you the exact error message returned by the API. I'm guessing you got the client ID or secret incorrect.

I tried the verify settings button earlier while testing and it worked for me on OSX.

**Comment by LowellMontgomery** [comment]
@mcrosson Doh! Yeah, that was my fault. On OS X, if you double-click on a string, you can select it with command-C and paste with command-P (pretty much the same as Windows), but the dash character breaks a string and there is one toward the end of my Client ID, which I didn't notice when I copied (not quite all of) my ID and pasted it in the field. So, of course, that was it. And now it should work. My access token was generated. I'll give it a whirl now. 👍 

Now the question is why the plugin is providing conflicting messages, i.e. the "Success" message printed in the window and the error message displayed in the pop-up. Both appeared when I clicked on the "Verify Settings" button.

**Comment by mcrosson** [comment]
@LowellMontgomery probably a bug ;) We should open a new ticket for that circumstance.

**Comment by mcrosson** [comment]
Yes, I'm ok "polluting" the issue tracker with each thing we discover as we work through stuff.

**Comment by mcrosson** [comment]
@LowellMontgomery I've merged the OSX fixes into the master branch and tagged a release based on your feedback. Let me know if everything else looks good and I'll update the ticket as necessary after hearing back.

**Comment by LowellMontgomery** [comment]
Good. 👍 

BTW, I guess that the fill_horizontal usually takes an integer (not boolean), so that would be the boolean "math" issue, eh?

In the safx version, the values were (example):

```
            f:edit_field {
               fill_horizonal = 1,
               width_in_chars = 35,
               value = bind 'clientId',
            },
```

**Comment by LowellMontgomery** [comment]
@mcrosson Good. I think we can close this issue and I'll check out master and re-start work on the feature branch(es) where I'll try to implement the work I did on the safx plugin.

**Comment by mcrosson** [comment]
@LowellMontgomery nice find. I don't think we really need the flag at this point. The whole UI needs touchup all over the place and at this point I'm content to leave it as-is since it's functional and not too ugly. At some point I'll probably prioritize it but for now I just want to make sure OSX is 100% sorted out as well as begin on a few of the other things we've previously discussed.

**Comment by mcrosson** [comment]
Closed per @LowellMontgomery confirming OSX fixes worked.

**Comment by LowellMontgomery** [comment]
@mcrosson If that’s the case, I’m not sure why it also generated the “Success” message in the window. The Client ID and Secret are the same that I’ve been using with the safx plugin and I’m pretty sure they are correct, but I’ll double-check for any error on my side after trying to get something into the log, as you suggested.

I’ll get back to you shortly… :-)

**Comment by mcrosson** [comment]
@LowellMontgomery see #6 for tracking the "Success" message. I've found and corrected the problem you were seeing on 2016/10/24.
